spring.application.name=spring_rider
# DataSource
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


jwt.secret.key=${JWT_KEY:VEVTVF9ERUZBVUxUX0tFWV9hc2RsanF3ZWxrMSQyaW9jbnhhc2RAIzUzNCM2dSEh}
# 60 min (60 * 60 * 1000ms)
jwt.token.exp=${JWT_EXP:3600000}

#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
#spring.mvc.log-request-details=true


